# Enable the build cache to save time by reusing outputs produced by other successful builds.
# https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching=true
# Enable the configuration cache to reuse the build configuration and enable parallel task execution.
# (Note that some plugins may not yet be compatible with the configuration cache.)
# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

maven_group=one.devos.nautical

clientier_archives_base_name=clientier
creepermultidrop_archives_base_name=creepermultidrop
dudewhatsmygepeuwu_archives_base_name=dudewhatsmygpuwu
nicespice_archives_base_name=nicespice
rainbethunder_archives_base_name=rainbethunder
clientier_version=1.0.0
creepermultidrop_version=1.5.0
dudewhatsmygepeuwu_version=1.2.0
nicespice_version=1.0.0
rainbethunder_version=1.3.0
